remote_theme: just-the-docs/just-the-docs
title: xronocode
description: Заметки и дискуссии

color_scheme: light
search_enabled: true
footer_content: ""
favicon_ico: "/favicon.ico"

plugins:
  - jekyll-remote-theme

nav_enabled: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: default
